name: leveldb_dart_example
description: Demonstrates how to use the leveldb_dart plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  leveldb_dart:
    # When depending on this package from a real application you should use:
    #   leveldb_dart: ^x.y.z
    path: ../
  path: ^1.8.0
