name: leveldb_dart
description: LevelDB for Dart using dart:ffi
version: 1.0.1
homepage: https://github.com/ethanblake4/leveldb_dart

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  ffi: ^2.1.3
  meta: ^1.8.0

dev_dependencies:
  ffigen: ^19.0.0

ffigen:
  output: lib/src/leveldb_bindings.dart
  name: 'LibLevelDB'
  description: 'Bindings to LevelDB'
  headers:
    entry-points:
      - leveldb/include/leveldb/c.h
  compiler-opts:
    - '-Ileveldb/include/'
